language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install codecov

install: "pip install -r requirements-dev.txt"

script:
  - coverage run setup.py test

after_success:
  - codecov
